baseURL = 'http://plabayo.tech/'
languageCode = 'en-us'
theme = "plabayo"
title = 'Plabayo Website'

defaultContentLanguage = 'en'

[languages]

    [languages.en]
        weight = 1

    [languages.es]
        weight = 2

    [languages.nl]
        weight = 2

[params]

    [params.eliza]
        name = 'Elizabeth C. Gonzales Belsuzarri'
        nameShort = 'Eliza'
        website = 'https://www.linkedin.com/in/elizabeth-gonzales-belsuzarri-72173214/'
        email = 'eliza@plabayo.tech'

    [params.glen]
        name = 'Glen Henri J. De Cauwsemaecker'
        nameShort = 'Glen'
        website = 'https://www.glendc.com/'
        email = 'contact@glendc.com'

    [params.plabayo]
        name = 'Plabayo'
        website = 'https://www.plabayo.tech/'
        email = 'contact@plabayo.tech'

    [params.license]
        name = 'Creative Commons Zero v1.0 Universal'
        url = 'https://github.com/plabayo/website/blob/main/LICENSE'

    [params.repository]
        url = 'https://github.com/plabayo/website'
